import {
  ElAffix,
  ElAvatar,
  ElButton,
  ElCol,
  ElContainer,
  ElDivider,
  ElFooter,
  ElForm,
  ElFormItem,
  ElHeader,
  ElIcon,
  ElInput,
  ElMain,
  ElMenu,
  ElMenuItem,
  ElPageHeader,
  ElRow,
  ElSubmenu,
} from "element-plus";
import lang from "element-plus/lib/locale/lang/ja";
import locale from "element-plus/lib/locale";
import { App } from "vue";

const components = [
  ElButton,
  ElContainer,
  ElHeader,
  ElMain,
  ElFooter,
  ElForm,
  ElFormItem,
  ElInput,
  ElIcon,
  ElSubmenu,
  ElMenu,
  ElMenuItem,
  ElDivider,
  ElRow,
  ElCol,
  ElAvatar,
  ElAffix,
  ElPageHeader,
  // ElAlert,
  // ElAside,
  // ElAutocomplete,

  // ElBacktop,
  // ElBadge,
  // ElBreadcrumb,
  // ElBreadcrumbItem,
  // ElButtonGroup,
  // ElCalendar,
  // ElCard,
  // ElCarousel,
  // ElCarouselItem,
  // ElCascader,
  // ElCascaderPanel,
  // ElCheckbox,
  // ElCheckboxButton,
  // ElCheckboxGroup,

  // ElCollapse,
  // ElCollapseItem,
  // ElCollapseTransition,
  // ElColorPicker,
  // ElContainer,
  // ElDatePicker,
  // ElDialog,

  // ElDrawer,
  // ElDropdown,
  // ElDropdownItem,
  // ElDropdownMenu,
  // ElHeader,

  // ElImage,
  // ElInputNumber,
  // ElLink,

  // ElMenuItemGroup,
  // ElOption,
  // ElOptionGroup,

  // ElPagination,
  // ElPopconfirm,
  // ElPopover,
  // ElPopper,
  // ElProgress,
  // ElRadio,
  // ElRadioButton,
  // ElRadioGroup,
  // ElRate,

  // ElScrollbar,
  // ElSelect,
  // ElSlider,
  // ElStep,
  // ElSteps,

  // ElSwitch,
  // ElTabPane,
  // ElTable,
  // ElTableColumn,
  // ElTabs,
  // ElTag,
  // ElTimePicker,
  // ElTimeSelect,
  // ElTimeline,
  // ElTimelineItem,
  // ElTooltip,
  // ElTransfer,
  // ElTree,
  // ElUpload,
  // ElInfiniteScroll,
  // ElLoading,
  // ElNotification,
];
export default (app: App<Element>) => {
  locale.use(lang);
  components.forEach((item) => app.use(item));
};
